import type { NextPage } from 'next';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';
import { FaGithub, FaGoogle } from 'react-icons/fa';
import SignedInLayout from '../components/SignedInLayout';

const Home: NextPage = () => {
  const { data } = useSession();

  if (!data)
    return (
      <div className="flex grow flex-col items-center justify-center">
        <div className="text-2xl font-bold">Please log in below</div>
        <div className="p-4" />
        <div className="flex flex-col gap-2">
          <button
            onClick={() => signIn('google')}
            className="flex items-center gap-2 rounded bg-gray-200 px-4 py-2 text-2xl text-black"
          >
            <span>Sign in with Google</span>
            <FaGoogle />
          </button>
          <button
            onClick={() => signIn('github')}
            className="flex items-center gap-2 rounded bg-gray-200 px-4 py-2 text-2xl text-black"
          >
            <span>Sign in with GitHub</span>
            <FaGithub />
          </button>
        </div>
      </div>
    );

  return (
    <>
      <Head>
        <title>Dude, where my stuff?!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedInLayout user={data.user}>a</SignedInLayout>
    </>
  );
};

export default Home;
